### ISSUE TITLE
Miku Overchan has broken post headers

### ISSUE THREAD

**Issue by makise-homura** [makise-homura/kurisaba#24]
Miku Overchan parses our post headers incorrectly (See https://github.com/miku-nyan/Overchan-Android/issues/117).
We might fix it on our side, if they still don't plan to work on it.

**Comment by aoi-miko** [comment]
Homu, that's because the project is abandoned by its creators.
There's a fork of Overchan which parses our posts correctly, I've tested all problems above mentioned.

You can download it from F-Droid as "Overchan (Fork)"

**Comment by makise-homura** [comment]
Uhm. I think this could be added into FAQ on Kurisach. (wrote into comments of #22).
