### ISSUE TITLE
Minor bugs in formatting

### ISSUE THREAD

**Issue by makise-homura** [makise-homura/kurisaba#43]
* Different order of post ordinal number and 'hide' button
* `&nbsp`s in post headers
* Overlapping of buttons in floating postbox
![default](https://user-images.githubusercontent.com/16463967/40213969-f145ba0a-5a60-11e8-9cb1-3160b0aa71f7.png)

**Comment by aoi-miko** [comment]
Oh. For me those bugs are seems to be closed. 
As far as I can remember, I was fixing them at some time.

**Comment by makise-homura** [comment]
Yeah, seems to be fixed already.
