### ISSUE TITLE
Will there be a demo site of kurisaba?

### ISSUE THREAD

**Issue by incestia** [makise-homura/kurisaba#50]
It'll be nice to see one

**Comment by makise-homura** [comment]
There once was a board on https://kurisa.ch; but now it's offline.
But, there's another board that uses kurisaba now: https://rf.dobrochan.nl
I guess it may count as a 'demo site'.

**Comment by makise-homura** [comment]
(closing as the problem seems to be resolved; if not, feel free to reply.)
